// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vphiecnvfshcfsmjmmka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwaGllY252ZnNoY2ZzbWptbWthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzM2NTcsImV4cCI6MjA2MDc0OTY1N30.MHtlq-8uZ6gqCzGraUf3nyiUdY2IwUh22QRyyF88gx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);